
version: "2.1"
services:
  dvna:
    build:
      context: ./
      dockerfile: Dockerfile  # Building my own app image
    ports:
      - "9090:9090"  # Expose DVNA on port 9090
    depends_on:
      - db
    networks:
      - dvnaNetwork
    environment:
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      - POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
      - POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}

  db:
    image: postgres:13
    container_name: dvna_db
    networks:
      - dvnaNetwork
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}

networks:
  dvnaNetwork:
    driver: bridge

volumes:
  db_data: