
version: "2.1"
services:
  dvna:
    build:
      context: ./
      dockerfile: Dockerfile  # Building my own app image
    ports:
      - "9090:9090"  # Expose DVNA on port 9090
    depends_on:
      - db
    networks:
      - dvnaNetwork
    env_file:
      - ./vars.env

  db:
    image: postgres:13
    container_name: dvna_db
    networks:
      - dvnaNetwork
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./vars.env  # Use this env file for the database

networks:
  dvnaNetwork:
    driver: bridge

volumes:
  db_data: