version: '3.8'

services:

  dvna:
    image: ./  # Use the official DVNA image
    ports:
      - "9090:9090"  # Expose DVNA on port 9090
    depends_on:
      - postgres
    networks:
      - dvna-network
    env_file:
      - ./vars.env
    deploy:
      resources:
        limits:
          cpus: '2.0'                  # Limit to 1 CPU core
          memory: 4G                   # Limit to 4 GB of RAM

  postgres:
    image: postgres:latest
    container_name: dvna_db
    networks:
      - dvna-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_backup:/backup
    env_file:
      - ./vars.env  # Use this env file for the database
    deploy:
      resources:
        limits:
          cpus: '1'         # Limit to 0.5 CPU core
          memory: 2G           # Limit to 1 GB of RAM

networks:
  dvna-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  db_backup:
    driver: local