name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull docker.io/naabda92/log8100_tp2:latest

      - name: Login to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token

      - name: Login to Heroku Container Registry
        run: |
          heroku container:login

      - name: Tag and Push Docker image to Heroku
        run: |
          docker tag docker.io/naabda92/log8100_tp2:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release the Docker image on Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Run database migrations (if needed)
        run: |
          heroku run npm run migrate --app ${{ secrets.HEROKU_APP_NAME }}