name: "ZAP Baseline Scan"

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Zap scanning
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          target: 'http://log8100-tp210.eastus.azurecontainer.io:9090/'
          cmd_options: '-a -j'
          
